/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework:spring-context:4.3.30.RELEASE")
    api("org.springframework:spring-webmvc:4.3.30.RELEASE")
    api("org.aspectj:aspectjrt:1.6.10")
    api("org.slf4j:slf4j-api:1.6.6")
    api("javax.inject:javax.inject:1")
    api("javax.servlet:jstl:1.2")
    api("xerces:xercesImpl:2.12.2")
    api("com.oracle.database.jdbc:ojdbc8:23.2.0.0")
    api("org.springframework:spring-jdbc:4.3.30.RELEASE")
    api("org.mybatis:mybatis:3.5.13")
    api("com.zaxxer:HikariCP:4.0.3")
    api("org.apache.logging.log4j:log4j-slf4j-impl:2.20.0")
    api("org.apache.logging.log4j:log4j-core:2.20.0")
    api("org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4:1.16")
    api("org.mybatis:mybatis-spring:2.1.1")
    api("org.mariadb.jdbc:mariadb-java-client:3.1.4")
    api("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    api("commons-io:commons-io:2.13.0")
    api("commons-fileupload:commons-fileupload:1.5")
    api("com.jcraft:jsch:0.1.55")
    runtimeOnly("org.slf4j:jcl-over-slf4j:1.6.6")
    runtimeOnly("org.slf4j:slf4j-log4j12:1.6.6")
    runtimeOnly("log4j:log4j:1.2.15")
    testImplementation("junit:junit:4.7")
    compileOnly("javax.servlet:servlet-api:2.5")
    compileOnly("javax.servlet.jsp:jsp-api:2.1")
}

group = "com.itbank"
version = "1.0.0-BUILD-SNAPSHOT"
description = "GoCamping"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
